server:
  port: 9080

spring:
  application:
    name: school-course-subscription-api
  cloud:
    config:
      name: school-course-subscription
      uri: http://localhost:8088
  profiles:
    active: dev
